### ISSUE TITLE
Just info.. 

### ISSUE THREAD

**Issue by wmdhosting** [mmikkel/CpClearCache-Craft#16]
![Snag_55a37b2](https://github.com/mmikkel/CpClearCache-Craft/assets/76176291/30fb33e6-8f96-42ca-a893-20e22d36a9a4)

**Comment by mmikkel** [comment]
Thanks for reporting, but for future reference please create separate issues for separate problems 🙂

The first issue ("Can't select Hyper") is fixed in CP Clear Cache 2.0.1 and 1.3.1. This was technically a UI bug: when the "All" option is selected all the checkboxes below are technically selected as well; the Hyper one just didn't visually appear as such.

Re: the missing icon, I'm pretty sure this must be a bug in CP Nav for Craft 5, where it looks like CP Nav doesn't handle existing [nav items using font icons](https://github.com/mmikkel/CpClearCache-Craft/blob/1ed155059dcdab2de7dc85c427d6299a3e829b6a/src/CpClearCache.php#L106) properly. You should create an issue over at [CP Nav's repo](https://github.com/verbb/cp-nav) for that.
