### ISSUE TITLE
Inputs outside of clear cache panel disabled

### ISSUE THREAD

**Issue by sarahschuetz** [mmikkel/CpClearCache-Craft#5]
After updating to Craft CMS to 3.5.17.1 and CP Clear Cache from 1.0.6 to 1.0.7 I am experiencing problems with disabled inputs outside of the range of the CP Clear Cache plugin. I am using Blitz and the Blitz Cache Utility Actions are disabled as soon as I enable the CP Clear Cache plugin (see [this issue](https://github.com/putyourlightson/craft-blitz/issues/283)). Without the plugin the Blitz Cache Actions work fine.

Can you please check if the plugin also affects forms / inputs outside of it's scope?

**Comment by mmikkel** [comment]
Hm, I did some digging and this is actually a bug (or at least, unexpected behaviour) in Craft. Basically, P&T changed the native Clear Caches utility JS in [this commit](https://github.com/craftcms/cms/commit/5f3a845277611d4c8b0890ffc271f160008f98bb#diff-e2a01e12aedc66a3d64e7a3a62232580d8c6093a20a7d149b37a3068bc7a77a6) so that it no longer queries the DOM for a single `<form>` by ID, but rather just does `$('form.utility')` – basically instantiating the Clear Caches tool on _all_ forms on the current page, that has the class `.utility` (note that the Clear Caches JS class still takes a `formId` parameter, but it doesn't use it for anything, which is why I'd call this a bug.

I'm not sure if it's worth reporting this to P&T; the Clear Caches JS is obviously written with the assumption that it'll only ever be instantiated on the Clear Caches utility page, where the only `.utility` form is the clear caches form – not that it'd get instantiated on _all_ CP pages, which CP Clear Cache does.

I'll have a think and see if I can come up with a workaround.

**Comment by mmikkel** [comment]
@sarahschuetz Should be resolved in [CP Clear Cache 1.1.0](https://github.com/mmikkel/CpClearCache-Craft/releases/tag/1.1.0) – thanks for reporting!
